language: python
python:
  - "3.4"
  - "3.6"
install: 
  - pip install -r requirements.txt
  - pip install coverage
script:
  - python test_bancocentral.py
  - coverage run bancocentral.py test
after_success: coverage report
notifications:
    email: true
