language: python
python:
  - "3.4"
  - "3.6"
install: 
  - pip install -r requirements.txt
  - pip install codecov
script:
  - python test_bancocentral.py
after_success: 
  - coverage run test_bancocentral.py
  - codecov
notifications:
    email: true
